### ISSUE TITLE
Sometimes Demo is not working

### ISSUE THREAD

**Issue by vkarampinis** [kolodny/deact#1]
Hello,
I am getting this error on Demo page
![screen shot 2016-01-17 at 15 25 34](https://cloud.githubusercontent.com/assets/330736/12377683/c9328dda-bd2e-11e5-8880-db164aefe2c1.png)
You can reproduce if you keep refreshing with dev tools open.
It seems that something loading faster/slower than expected.

**Comment by kolodny** [comment]
Which browser and version are you using?

**Comment by vkarampinis** [comment]
Chrome Version 47.0.2526.111

**Comment by kolodny** [comment]
Great find! It seems that when the placeholder would start with a number the onclick attribute would be something like `8ndt5egtcw2hjjor-2`, when accessing this value as a property on the DOM element, it would try to set it as the body of an `onclick` function, this is a syntax error. There are two solutions to this, the first is ensuring that the placeholder starts with a letter, the other is to use `getAttribute`, 6e060e4361e5f029e04de7b92a4c5420648e0adf does both of these things. Better safe than sorry. Thanks
